"""389. Find the Difference
Link: https://leetcode.com/problems/find-the-difference/
Difficulty: Easy
Description: You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t."""


class Solution:
    @staticmethod
    def findTheDifference(s: str, t: str) -> str:
        """Optimal Solution: Hash Table. Time Complexity: O(n), Space Complexity: O(n)."""
        # Create a dictionary to count occurrences of each character in s
        char_count = {}
        for char in s:
            char_count[char] = char_count.get(char, 0) + 1

        # Check if t contains the extra character
        for char in t:
            if char not in char_count or char_count[char] == 0:
                return char
            char_count[char] -= 1
        return ""


def unit_tests():
    # Input: s = "abcd", t = "abcde", Output: "e"
    assert Solution.findTheDifference("abcd", "abcde") == "e"

    # Input: s = "", t = "y", Output: "y"
    assert Solution.findTheDifference("", "y") == "y"

    # Input: s = "a", t = "aa", Output: "a"
    assert Solution.findTheDifference("a", "aa") == "a"


if __name__ == "__main__":
    unit_tests()
    print("All unit tests are passed.")
